# Generated by Django 3.0.2 on 2020-01-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200114_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_usa',
            new_name='fess_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_world',
            new_name='fess_in_world',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tagLine',
            new_name='tagline',
        ),
    ]
